#!/usr/bin/env python3
"""
Security Setup Script
Generates required secrets and helps configure the bot securely
"""

import secrets
import os
from pathlib import Path
from cryptography.fernet import Fernet


def generate_secrets():
    """Generate all required secrets"""
    print("="*70)
    print("🔐 SCALPING BOT - SECURITY SETUP")
    print("="*70)
    print()

    # Check if secrets.env already exists
    secrets_file = Path("config/secrets.env")
    if secrets_file.exists():
        print("⚠️  WARNING: config/secrets.env already exists!")
        response = input("Overwrite existing secrets? (yes/no): ")
        if response.lower() != 'yes':
            print("Setup cancelled.")
            return

    # Generate Flask secret key
    flask_secret = secrets.token_hex(32)
    print("✅ Generated Flask Secret Key (64 characters)")

    # Generate encryption key
    encryption_key = Fernet.generate_key().decode()
    print("✅ Generated Fernet Encryption Key")

    print()
    print("="*70)
    print("📝 NEXT STEPS:")
    print("="*70)
    print()
    print("1. Copy config/secrets.env.example to config/secrets.env")
    print("2. Fill in the following values:")
    print()
    print("   KITE_API_KEY=<your_zerodha_api_key>")
    print("   KITE_API_SECRET=<your_zerodha_api_secret>")
    print(f"   FLASK_SECRET_KEY={flask_secret}")
    print(f"   ENCRYPTION_KEY={encryption_key}")
    print()

    # Ask if user wants to auto-create the file
    response = input("Auto-create config/secrets.env with generated keys? (yes/no): ")

    if response.lower() == 'yes':
        create_secrets_file(flask_secret, encryption_key)
    else:
        print()
        print("="*70)
        print("💾 SAVE THESE VALUES (they won't be shown again!):")
        print("="*70)
        print()
        print(f"FLASK_SECRET_KEY={flask_secret}")
        print(f"ENCRYPTION_KEY={encryption_key}")
        print()
        print("Add these to config/secrets.env manually")


def create_secrets_file(flask_secret, encryption_key):
    """Create secrets.env file with generated values"""
    secrets_content = f"""# Scalping Bot Secrets
# Generated by setup_security.py
# NEVER commit this file to version control!

# Zerodha API Credentials (get from https://kite.trade/docs/connect/v3/)
KITE_API_KEY=your_api_key_here
KITE_API_SECRET=your_api_secret_here
KITE_ACCESS_TOKEN=  # Generated after login, leave empty initially

# Flask Security (GENERATED - DO NOT CHANGE)
FLASK_SECRET_KEY={flask_secret}

# Encryption Key (GENERATED - DO NOT CHANGE)
ENCRYPTION_KEY={encryption_key}

# Telegram Bot (Optional)
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# Email Alerts (Optional)
EMAIL_SMTP_SERVER=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_FROM=
EMAIL_PASSWORD=

# Database (If using PostgreSQL)
DB_HOST=localhost
DB_PORT=5432
DB_NAME=trading
DB_USERNAME=postgres
DB_PASSWORD=

# Dashboard Authentication (Recommended for production)
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=  # Use strong password in production
"""

    secrets_file = Path("config/secrets.env")

    try:
        # Create config directory if it doesn't exist
        secrets_file.parent.mkdir(parents=True, exist_ok=True)

        # Write secrets file
        with open(secrets_file, 'w') as f:
            f.write(secrets_content)

        # Set restrictive permissions (Unix-like systems)
        try:
            os.chmod(secrets_file, 0o600)
            print(f"✅ Created {secrets_file} with secure permissions (600)")
        except:
            print(f"✅ Created {secrets_file}")
            print("⚠️  Set file permissions to 600 (read/write for owner only)")

        print()
        print("="*70)
        print("⚠️  IMPORTANT: Fill in your Zerodha API credentials:")
        print("="*70)
        print()
        print(f"Edit {secrets_file} and add:")
        print("  - KITE_API_KEY (from Zerodha Kite Connect)")
        print("  - KITE_API_SECRET (from Zerodha Kite Connect)")
        print()
        print("All other secrets have been pre-filled.")

    except Exception as e:
        print(f"❌ Error creating secrets file: {e}")


def verify_installation():
    """Verify all dependencies are installed"""
    print()
    print("="*70)
    print("🔍 VERIFYING DEPENDENCIES")
    print("="*70)
    print()

    dependencies = [
        ('Flask', 'Flask'),
        ('Flask-WTF', 'flask_wtf'),
        ('Flask-Limiter', 'flask_limiter'),
        ('Cryptography', 'cryptography'),
        ('Python-dotenv', 'dotenv'),
    ]

    all_installed = True

    for name, import_name in dependencies:
        try:
            __import__(import_name)
            print(f"✅ {name}")
        except ImportError:
            print(f"❌ {name} - NOT INSTALLED")
            all_installed = False

    print()

    if not all_installed:
        print("⚠️  Missing dependencies detected!")
        print()
        print("Install with:")
        print("  pip install -r requirements_security.txt")
    else:
        print("✅ All security dependencies installed!")


def check_gitignore():
    """Verify .gitignore includes secrets"""
    print()
    print("="*70)
    print("🔍 CHECKING .gitignore")
    print("="*70)
    print()

    gitignore = Path(".gitignore")

    if not gitignore.exists():
        print("⚠️  No .gitignore found!")
        print("Creating .gitignore with security rules...")
        create_gitignore()
        return

    with open(gitignore, 'r') as f:
        content = f.read()

    required_entries = [
        'secrets.env',
        '.access_token',
        '.env'
    ]

    missing = []
    for entry in required_entries:
        if entry not in content:
            missing.append(entry)

    if missing:
        print("⚠️  .gitignore is missing these entries:")
        for entry in missing:
            print(f"   - {entry}")
        print()
        print("Add these to .gitignore to prevent accidental commits!")
    else:
        print("✅ .gitignore properly configured")


def create_gitignore():
    """Create .gitignore with security rules"""
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/

# Virtual Environment
venv/
env/
ENV/

# IDE
.vscode/
.idea/
*.swp
.DS_Store

# Logs
logs/
*.log

# SECURITY: Never commit secrets!
.env
config/secrets.env
*.key
*.pem
.access_token
access_token.json
session_data.json

# Trading data
data/
backtest_results/
trades.db
"""

    with open(".gitignore", 'w') as f:
        f.write(gitignore_content)

    print("✅ Created .gitignore with security rules")


def main():
    """Main setup function"""
    try:
        # Generate secrets
        generate_secrets()

        # Verify dependencies
        verify_installation()

        # Check .gitignore
        check_gitignore()

        print()
        print("="*70)
        print("🎉 SECURITY SETUP COMPLETE!")
        print("="*70)
        print()
        print("Next steps:")
        print("1. Edit config/secrets.env and add your Zerodha API credentials")
        print("2. Run: python run_dashboard.py")
        print("3. Navigate to: http://localhost:8050")
        print()
        print("⚠️  IMPORTANT: Never commit config/secrets.env to Git!")
        print()

    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")


if __name__ == '__main__':
    main()
